## Numpy of zamato Dataset 


In [2]:
import numpy as np 
import matplotlib as plt 

In [ ]:
#Data structure : [restaurant_id , 2021 , 2022, 2023, 2024,]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani 
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites 
    [3, 200000, 230000, 260000, 300000],  # Burger Point 
    [4, 110000, 135000, 155000, 180000],  # Pizza Palace
    [5, 175000, 195000, 225000, 265000],  # Taco Town
])
print("==== ZOMATO SALES ANALYSIS ====")
print("zomato data shape : " , sales_data.shape)
print(sales_data[: , 1:]) #iska matlab hai  : matlab sare rows dedo or , 1: is matlab hai rows ke andar 1 se start karo aur sare dedo [m , n] [rows , coloumn ]

==== ZOMATO SALES ANALYSIS ====
zomato data shape :  (5, 5)
[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [110000 135000 155000 180000]
 [175000 195000 225000 265000]]
