## Numpy array basics 
learning numpy with chai aur code 


In [2]:

import sys
print("Python executable:", sys.executable)
print("Should contain 'venv':", 'venv' in sys.executable)

Python executable: c:\Users\Admin\Desktop\numpy\Numpy\venv\Scripts\python.exe
Should contain 'venv': True


In [1]:
import numpy as np
print("Numpy version:", np.__version__)

Numpy version: 2.3.3


In [4]:
arr_1d=np.array([1,2,3,4,5])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,3] ,[4,5,6]])
print(arr_2d)

1D array: [1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## list vs numpy

In [8]:
py_list = [1,2,3]
print("Python array multiplication : ",py_list*2)

Python array multiplication :  [1, 2, 3, 1, 2, 3]


In [10]:
## element wise multiplication 
np_array= np.array([1,2,3])
print("Python array multiplication : ",np_array*2)

Python array multiplication :  [2 4 6]


In [14]:
import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ",time.time()-start)

start = time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time : ",time.time()-start)



 List operation time :  0.40405988693237305

 Numpy operation time :  0.007233858108520508


## Creating arrays from scratch 


In [27]:
## arrays of zeroes , one or full , random 
zeros= np.zeros((3,4))
print(" Zero array :\n", zeros)

one = np.ones((2,3))
print(" ones array :\n", one)

full = np.full((2,2),7)
print("Full array :\n",full)

random = np.random.random((2,3))
print("random : \n" , random )

sequence = np.arange(0,11,2)
print("sequence : ",sequence)

 Zero array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 ones array :
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array :
 [[7 7]
 [7 7]]
random : 
 [[0.12427015 0.58588716 0.56244467]
 [0.37658203 0.8819508  0.95508951]]
sequence :  [ 0  2  4  6  8 10]


### Vector , Matrix , Tensor 

In [33]:
vector = np.array([1,2,3])
print("vector :",vector)

matrix = np.array([[1,2,3] ,[4,5,6]])
print("matrix : \n",matrix)

tensor = np.array([[[1,2] ,[3,4]],[[5,6],[7,8]]])
print("Tensor : \n ",tensor)
print(tensor.shape)

vector : [1 2 3]
matrix : 
 [[1 2 3]
 [4 5 6]]
Tensor : 
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


## Array Properties 

In [42]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)
print(arr)

Shape (2, 3)
Dimension 2
size 6
Dtype int64
[[1 2 3]
 [4 5 6]]


In [52]:
arr= np.arange(12)
print(arr)
reshaped = arr.reshape((3,4))
print("\n reshaped array :",reshaped)

flattened = reshaped.flatten()
print(flattened)  # it creates a copy 

# it creates the view instead of the copy 
ravel = reshaped.ravel()
print("Raveled array :\n",ravel)

transposed = reshaped.T
print("transposed array ", transposed)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
