In [4]:
import numpy as np
np_array= np.array([1,2,3])
print("Python array multiplication : ",np_array*2)

Python array multiplication :  [2 4 6]


In [11]:
array = np.arange(0,11)
print(array)    
print(array[2:8])


[ 0  1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6 7]


In [21]:
arr_2d = np.array([[1,2,3],[4,5,6],[3,6,7]])
print(arr_2d)
print("element in the array :",arr_2d[1,2])
print("Entire row :",arr_2d[1])
print(" col specific: ",arr_2d[:,1])


[[1 2 3]
 [4 5 6]
 [3 6 7]]
element in the array : 6
Entire row : [4 5 6]
 col specific:  [2 5 6]


## Sorted array 

In [22]:
unsorted = np.array([3,1,4,5,2,6,7])
print("sorted array :",np.sort(unsorted))

sorted array : [1 2 3 4 5 6 7]


In [25]:
arr_2d_unsorted = np.array([[3,1],[4,5],[2,7]])
print("sorted 2D array by col :\n",np.sort(arr_2d_unsorted , axis=0)) # and in row wise sorting we use axis=1

sorted 2D array by col :
 [[2 1]
 [3 5]
 [4 7]]


In [27]:
number = np.array([1,2,3,4,5,6,7,8])
even_number= number[number % 2 ==0]
print(even_number)

[2 4 6 8]


In [28]:
print(number)

[1 2 3 4 5 6 7 8]


In [ ]:
mask = number >5 # it gives the indexes of greter than 5 
print(number[mask])

[6 7 8]


## Fancy indexing vs np.where()


In [33]:
indices =[0,1,2]
print(number[indices])

where_result = np.where( number >5)
print("no greater than 5 :",number[where_result])

[1 2 3]
no greater than 5 : [6 7 8]


In [34]:
condition_array =np.where(number > 5, "ture" , "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'ture' 'ture' 'ture']


## Array compatibility

In [40]:
a = np.array([1,2,3])
b=np.array([4,5,6,3])
print(a.shape)
print("compatibility shaped :",a.shape == b.shape)

(3,)
compatibility shaped : False


In [57]:
original = np.array([[1,2],[3,4]]) # two dimensional array 
new_row = np.array([5,6]) #one dimensional array 
combined = np.vstack((original , new_row)) # it adds the new row to the matrix 
print(combined)

new_col = np.array([[7],[8]]) #2D array with one col 
print(new_col)
print(new_col.shape) # it gives no of rows , no of col 
with_new_col = np.hstack((original , new_col))
print(with_new_col)


[[1 2]
 [3 4]
 [5 6]]
[[7]
 [8]]
(2, 1)
[[1 2 7]
 [3 4 8]]


In [61]:
arr= np.array([1,2,3,4,5])
deleted = np.delete(arr,[2,4])
print("return the array after delteting the values from it : ",deleted)

return the array after delteting the values from it :  [1 2 4]
